# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{flukso4r}
  s.version = "0.3.6"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Mathias Dalheimer"]
  s.date = %q{2010-06-08}
  s.default_executable = %q{flukso_query}
  s.description = %q{This gem provides a library for the Flukso API. See http://flukso.net for more information.}
  s.email = %q{md@gonium.net}
  s.executables = ["bin/flukso_archive_watts", "bin/flukso_create_db", "bin/flukso_export_db", "bin/flukso_plot", "bin/flukso_query"]
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "bin/flukso_archive_watts",
     "bin/flukso_create_db",
     "bin/flukso_export_db",
     "bin/flukso_plot",
     "bin/flukso_query",
     "etc/flukso4rrc",
     "lib/flukso.rb",
     "lib/flukso/api.rb",
     "lib/flukso/database.rb",
     "lib/flukso/export.rb",
     "lib/flukso/http_auth.rb",
     "lib/flukso/reading.rb",
     "lib/flukso/request.rb",
     "test/helper.rb",
     "test/test_flukso4r.rb"
  ]
  s.homepage = %q{http://gonium.net/md/flukso4r}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{A Ruby Library for the Flukso Webservice}
  s.test_files = [
    "test/helper.rb",
     "test/test_flukso4r.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<httparty>, ["~> 0.4.3"])
      s.add_runtime_dependency(%q<sqlite3-ruby>, ["~> 1.2.5"])
    else
      s.add_dependency(%q<httparty>, ["~> 0.4.3"])
      s.add_dependency(%q<sqlite3-ruby>, ["~> 1.2.5"])
    end
  else
    s.add_dependency(%q<httparty>, ["~> 0.4.3"])
    s.add_dependency(%q<sqlite3-ruby>, ["~> 1.2.5"])
  end
end

